services:
  postgres:
    image: postgres:15
    container_name: pawpal_db
    environment:
      POSTGRES_USER: pawpal_user
      POSTGRES_PASSWORD: pawpal_password
      POSTGRES_DB: pawpal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: